area = 1            # suface area of gridcell, 1 cm2 in Morris & Bowden [in cm2] 

# Values taken from Morris & Bowden (1986) Table 1.
bo = 0.07182    # bulk density of organic matter [in g/cm3]
bi = 0.1        # bulk density of inorganic matter, not defined in Morris & Bowden [in g/cm3] 
fc = 0.2        # portion of organic material that is refactory [in g/g] 

[biomass]
Ro = 0.0105         # live below ground biomass at sediment surface [in g/cm]
k1 = 0.1            # distribution parameter for below ground biomass [in 1/cm]
root_depth = 30.0   # maximum root depth for new plants [in cm].
k3 = 0.0344         # portion ash (inorganic) content in plant matter [in g/g].
k2 = 0.5            # natural turnover rate of live belowground biomass [in 1/yr].

[initial_conditions]
Wa = 0.1    # initial deposition of organic matter onto marsh surface [in g/cm2]
k4 = 0.02   # initial deposition of inorganic matter onto marsh surface [in g/cm2]
Du = 0.0    # elevation of top of initial layer, not specified in Morris & Bowden [in cm].
Db = -30.0  # elevation of bottom of initial layer, not specifically defined in Morris & Bowden but only the first 30 is assumed to be alive [in cm].